/**
 * Stage 2 — Mesh quality tests
 *
 * Prerequisites:
 *   - Docker must be running
 *   - tests/fixtures/generated/cavity/ must exist (run test:stage1 first)
 *
 * No API calls. Reuses files generated by Stage 1.
 * Expected runtime: ~60 seconds.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import Dockerode from 'dockerode'
import * as fs from 'fs'
import * as path from 'path'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const IMAGE = 'microfluidica/openfoam:13'
const OF_BASHRC = '/opt/openfoam13/etc/bashrc'
const FIXTURES_DIR = path.join(process.cwd(), 'tests', 'fixtures', 'generated', 'cavity')

// ---------------------------------------------------------------------------
// Docker helpers (same pattern as Stage 0)
// ---------------------------------------------------------------------------

const docker = new Dockerode()

async function execInContainer(
  container: Dockerode.Container,
  cmd: string[]
): Promise<{ exitCode: number; stdout: string }> {
  const exec = await container.exec({
    Cmd: cmd,
    AttachStdout: true,
    AttachStderr: true,
  })
  const stream = await exec.start({ hijack: true, stdin: false })
  let raw = ''
  await new Promise<void>((resolve, reject) => {
    docker.modem.demuxStream(
      stream,
      { write: (chunk: Buffer) => { raw += chunk.toString() } },
      { write: (chunk: Buffer) => { raw += chunk.toString() } }
    )
    stream.on('end', resolve)
    stream.on('error', reject)
  })
  const inspect = await exec.inspect()
  return { exitCode: inspect.ExitCode ?? -1, stdout: raw }
}

async function startFreshContainer(binds: string[] = []): Promise<Dockerode.Container> {
  const container = await docker.createContainer({
    Image: IMAGE,
    Cmd: ['tail', '-f', '/dev/null'],
    Tty: false,
    HostConfig: { Binds: binds },
  })
  await container.start()
  return container
}

async function cleanupContainer(container: Dockerode.Container): Promise<void> {
  try { await container.stop({ t: 5 }) } catch { /* already stopped */ }
  try { await container.remove() } catch { /* already removed */ }
}

// ---------------------------------------------------------------------------
// Shared state: one container reused across all 3 tests
// ---------------------------------------------------------------------------

let container: Dockerode.Container | null = null
let blockMeshLog = ''
let blockMeshExitCode = -1
let checkMeshLog = ''
let checkMeshExitCode = -1

beforeAll(async () => {
  console.log('\n[Stage 2] Verifying fixture files exist...')

  // Fail fast if Stage 1 hasn't been run yet
  if (!fs.existsSync(FIXTURES_DIR)) {
    throw new Error(
      `Fixture directory not found: ${FIXTURES_DIR}\n` +
      `Run "npm run test:stage1" first to generate the cavity case files.`
    )
  }

  const requiredFiles = [
    path.join('0', 'U'),
    path.join('0', 'p'),
    path.join('constant', 'physicalProperties'),
    path.join('constant', 'momentumTransport'),
    path.join('system', 'controlDict'),
    path.join('system', 'fvSchemes'),
    path.join('system', 'fvSolution'),
    path.join('system', 'blockMeshDict'),
  ]

  for (const relPath of requiredFiles) {
    const full = path.join(FIXTURES_DIR, relPath)
    if (!fs.existsSync(full)) {
      throw new Error(`Missing fixture file: ${full}`)
    }
  }
  console.log(`[Stage 2] All 8 fixture files found in ${FIXTURES_DIR}`)

  // Mount the fixtures directory into the container as /case
  const bind = `${FIXTURES_DIR}:/case:ro`
  console.log('[Stage 2] Starting container...')
  container = await startFreshContainer([bind])
  console.log(`[Stage 2] Container: ${container.id.slice(0, 12)}`)

  // Copy files from /case (read-only mount) into /root/cavity (writable working dir)
  // OpenFOAM writes mesh files in-place so needs a writable case dir
  console.log('[Stage 2] Copying fixture files to writable case directory...')
  const copyResult = await execInContainer(container, [
    'bash', '-c', 'cp -r /case /root/cavity',
  ])
  if (copyResult.exitCode !== 0) {
    throw new Error(`Failed to copy case files: ${copyResult.stdout}`)
  }

  // Run blockMesh
  console.log('[Stage 2] Running blockMesh on generated files...')
  const bmResult = await execInContainer(container, [
    'bash', '-c',
    `cd /root/cavity && source ${OF_BASHRC} && blockMesh > /root/blockMesh.log 2>&1; echo "EXIT:$?"`,
  ])
  const logResult = await execInContainer(container, ['cat', '/root/blockMesh.log'])
  blockMeshLog = logResult.stdout
  blockMeshExitCode = parseInt(
    (bmResult.stdout.match(/EXIT:(\d+)/) ?? [, '-1'])[1] ?? '-1', 10
  )
  console.log(`[Stage 2] blockMesh exit code: ${blockMeshExitCode}`)
  console.log('[Stage 2] blockMesh log (last 8 lines):')
  blockMeshLog.split('\n').slice(-8).forEach(l => console.log(`  ${l}`))

  // Run checkMesh (only if blockMesh succeeded)
  if (blockMeshExitCode === 0) {
    console.log('[Stage 2] Running checkMesh...')
    const cmResult = await execInContainer(container, [
      'bash', '-c',
      `cd /root/cavity && source ${OF_BASHRC} && checkMesh > /root/checkMesh.log 2>&1; echo "EXIT:$?"`,
    ])
    const cmLogResult = await execInContainer(container, ['cat', '/root/checkMesh.log'])
    checkMeshLog = cmLogResult.stdout
    checkMeshExitCode = parseInt(
      (cmResult.stdout.match(/EXIT:(\d+)/) ?? [, '-1'])[1] ?? '-1', 10
    )
    console.log(`[Stage 2] checkMesh exit code: ${checkMeshExitCode}`)
    console.log('[Stage 2] checkMesh log (last 10 lines):')
    checkMeshLog.split('\n').slice(-10).forEach(l => console.log(`  ${l}`))
  }
}, 120_000)

afterAll(async () => {
  if (container) {
    await cleanupContainer(container)
    container = null
  }
})

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Stage 2 — Mesh Quality', () => {

  // -------------------------------------------------------------------------
  it('Test 1: blockMesh succeeds on generated files', () => {
    console.log('\n[Test 1] Asserting blockMesh result...')
    expect(blockMeshExitCode, 'blockMesh should exit 0').toBe(0)
    expect(blockMeshLog, 'blockMesh log should contain "End"').toContain('End')
    expect(blockMeshLog, 'blockMesh log must not contain FOAM FATAL ERROR').not.toContain('FOAM FATAL ERROR')
    console.log('[Test 1] PASS')
  })

  // -------------------------------------------------------------------------
  it('Test 2: checkMesh passes quality thresholds', () => {
    console.log('\n[Test 2] Asserting checkMesh result...')
    expect(checkMeshExitCode, 'checkMesh should exit 0').toBe(0)
    expect(checkMeshLog, 'checkMesh log must not contain FOAM FATAL ERROR').not.toContain('FOAM FATAL ERROR')

    // Parse max non-orthogonality
    const nonOrthoMatch = checkMeshLog.match(/Max non-orthogonality\s*=\s*([\d.]+)/)
    if (nonOrthoMatch) {
      const nonOrtho = parseFloat(nonOrthoMatch[1]!)
      console.log(`  Max non-orthogonality = ${nonOrtho}°`)
      expect(nonOrtho, `Max non-orthogonality (${nonOrtho}) must be < 70°`).toBeLessThan(70)
    }

    // Parse max skewness
    const skewnessMatch = checkMeshLog.match(/Max skewness\s*=\s*([\d.]+)/)
    if (skewnessMatch) {
      const skewness = parseFloat(skewnessMatch[1]!)
      console.log(`  Max skewness = ${skewness}`)
      expect(skewness, `Max skewness (${skewness}) must be < 4`).toBeLessThan(4)
    }

    // Mesh should be OK (zero failed checks or explicit "Mesh OK")
    const hasMeshOk = checkMeshLog.includes('Mesh OK') ||
      checkMeshLog.includes('No errors found') ||
      !checkMeshLog.includes('FAILED')
    expect(hasMeshOk, 'checkMesh should report no failures').toBe(true)

    console.log('[Test 2] PASS')
  })

  // -------------------------------------------------------------------------
  it('Test 3: Mesh statistics are reasonable for cavity case', () => {
    console.log('\n[Test 3] Asserting mesh statistics...')

    // Parse total cells
    const cellsMatch = checkMeshLog.match(/cells:\s*(\d+)/)
    if (cellsMatch) {
      const totalCells = parseInt(cellsMatch[1]!, 10)
      console.log(`  Total cells = ${totalCells}`)
      expect(totalCells, 'Total cells must be > 0').toBeGreaterThan(0)
      expect(totalCells, 'Total cells must be < 1,000,000 (sanity)').toBeLessThan(1_000_000)
    } else {
      // Some OF versions report differently — just ensure checkMesh ran
      expect(checkMeshLog.length, 'checkMesh log must not be empty').toBeGreaterThan(0)
    }

    // All expected boundary patches should be mentioned
    const boundaries = ['movingWall', 'fixedWalls', 'frontAndBack']
    for (const boundary of boundaries) {
      console.log(`  Checking for boundary: ${boundary}`)
      expect(
        checkMeshLog,
        `checkMesh output should mention boundary patch "${boundary}"`
      ).toContain(boundary)
    }

    console.log('[Test 3] PASS')
  })

})
